### ISSUE TITLE
Read and Write 3D image using ITK -- contradicts

### ISSUE THREAD

**Issue by PayamZandiyeh** [PayamZandiyeh/StereoFlouroscopyRegistration#11]
Currently, if I read a 3D model and then write it without doing anything, the physical location of the image and its direction is changed. 
- Try to figure out the source of problem (if it is a problem)
- Check if resample image filter will take care of it.

**Comment by Besler** [comment]
Would you be able to create an example of the issue?

**Comment by PayamZandiyeh** [comment]
```
# Example of Contradiction for Image Read and Image Write

# ---- imports 

import itk
import sys


# ----- Main Body of the code. 
verbose = False 

input_filename  = '/Volumes/Storage/Projects/Registration/QuickData/OA-BEADS-CT.nii'
output_filename = '/Volumes/Storage/Projects/Registration/QuickData/test.nii'


InputPixelType  = itk.ctype("short")
OutputPixelType = itk.ctype("short")
ScalarType = itk.D
DimensionIn  = 3
DimensionOut = 3

InputImageType  = itk.Image[InputPixelType , DimensionIn ]
OutputImageType = itk.Image[OutputPixelType, DimensionOut]


ReaderType = itk.ImageFileReader[InputImageType]
reader     = ReaderType.New()
reader.SetFileName(input_filename)

try:
    print("Reading image: " + input_filename)
    reader.Update()
    print("Image Read Successfully")
except ValueError: 
    print("ERROR: ExceptionObject cauth! \n")
    print(ValueError)
    sys.exit()
    
inputImage = reader.GetOutput()

if verbose :
    print(inputImage)
    
WriterType = itk.ImageFileWriter[OutputImageType]
writer = WriterType.New()

writer.SetFileName(output_filename)
writer.SetInput(reader.GetOutput())

try:
    print("Writing image: " + output_filename)
    writer.Update()
    print("Image Printed Successfully")
except ValueError: 
    print("ERROR: ExceptionObject cauth! \n")
    print(ValueError)
    sys.exit()
```
![screen shot 2018-02-14 at 9 51 08 am](https://user-images.githubusercontent.com/29908717/36213643-d7889f48-116c-11e8-9936-e24acab1c3c1.png)

**Comment by PayamZandiyeh** [comment]
@Besler I have tried with regular itk.imread and itk.imwrite and the outcome was the same.

**Comment by Besler** [comment]
Here is my example:
```python
# Example of Contradiction for Image Read and Image Write

# ---- imports 

import itk
import sys


# ----- Main Body of the code. 
verbose = False 

input_filename  = '/Users/babesler/Desktop/Registration3D2D/EDITED-OA-BEADS-CT.mha'
output_filename = '/Users/babesler/Desktop/Registration3D2D/test.nii'

image1 = itk.imread(input_filename)
itk.imwrite(image1, output_filename)
image2 = itk.imread(output_filename)

print(image1)
print(image2)
```

Output is:
```bash
Image (0x7fe75df845c0)
  RTTI typeinfo:   itk::Image<short, 3u>
  Reference Count: 1
  Modified Time: 353
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 179
  UpdateMTime: 352
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  Spacing: [0.292969, 0.292969, 0.6]
  Origin: [73.8535, 207.854, -603.8]
  Direction: 
-1 0 0
0 -1 0
0 0 1

  IndexToPointMatrix: 
-0.292969 0 0
0 -0.292969 0
0 0 0.6

  PointToIndexMatrix: 
-3.41333 0 0
0 -3.41333 0
0 0 1.66667

  Inverse Direction: 
-1 0 0
0 -1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x7fe75df84890)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, short>
      Reference Count: 1
      Modified Time: 349
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x11791d000
      Container manages memory: true
      Size: 88866816
      Capacity: 88866816

Image (0x7fe75b73b360)
  RTTI typeinfo:   itk::Image<short, 3u>
  Reference Count: 1
  Modified Time: 834
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 674
  UpdateMTime: 833
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  Spacing: [0.292969, 0.292969, 0.6]
  Origin: [73.8535, 207.854, -603.8]
  Direction: 
-1 0 0
0 -1 0
0 0 1

  IndexToPointMatrix: 
-0.292969 0 0
0 -0.292969 0
0 0 0.6

  PointToIndexMatrix: 
-3.41333 0 0
0 -3.41333 0
0 0 1.66667

  Inverse Direction: 
-1 0 0
0 -1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x7fe75b7244f0)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, short>
      Reference Count: 1
      Modified Time: 830
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x12229d000
      Container manages memory: true
      Size: 88866816
      Capacity: 88866816
```

**Comment by Besler** [comment]
The image data is the same on my computer. It is difficult to visualize the differences since Paraview doesn't account for image orientation. Could you print the images at the end of your script to verify the data is the same?

**Comment by PayamZandiyeh** [comment]
You are right! 
I am not sure what the heck is happening with Paraview ... The information seems identical but the physical appearance in Paraview is different. Here are the details: 


Image (0x7fc7fe216420)
  RTTI typeinfo:   itk::Image<short, 3u>
  Reference Count: 1
  Modified Time: 982
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 822
  UpdateMTime: 981
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  Spacing: [0.292969, 0.292969, 0.6]
  Origin: [73.8535, 207.854, -603.8]
  Direction: 
-1 0 0
0 -1 0
0 0 1

  IndexToPointMatrix: 
-0.292969 0 0
0 -0.292969 0
0 0 0.6

  PointToIndexMatrix: 
-3.41333 0 0
0 -3.41333 0
0 0 1.66667

  Inverse Direction: 
-1 0 0
0 -1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x7fc7fe214580)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, short>
      Reference Count: 1
      Modified Time: 978
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x12ca9d000
      Container manages memory: true
      Size: 88866816
      Capacity: 88866816

Image (0x7fc7fe7dc8e0)
  RTTI typeinfo:   itk::Image<short, 3u>
  Reference Count: 1
  Modified Time: 1306
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 1146
  UpdateMTime: 1305
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [512, 512, 339]
  Spacing: [0.292969, 0.292969, 0.6]
  Origin: [73.8535, 207.854, -603.8]
  Direction: 
-1 0 0
0 -1 0
0 0 1

  IndexToPointMatrix: 
-0.292969 0 0
0 -0.292969 0
0 0 0.6

  PointToIndexMatrix: 
-3.41333 0 0
0 -3.41333 0
0 0 1.66667

  Inverse Direction: 
-1 0 0
0 -1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x7fc7fe7dd950)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, short>
      Reference Count: 1
      Modified Time: 1302
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x12ca9d000
      Container manages memory: true
      Size: 88866816
      Capacity: 88866816

**Comment by PayamZandiyeh** [comment]
Puzzling!

**Comment by Besler** [comment]
I think Paraview has issues with reading image data sometimes. Especially if that data has a non-identity orientation matrix. Things are looking good, no need to fret.

**Comment by PayamZandiyeh** [comment]
You bet! Thanks for the quick reply
